---

- hosts: localhost
  gather_facts: true
  var: var.yml

  tasks:
    
    - name: clean rpms
      shell: yum clean all

    - name: Install packages
      action: yum pkg={{item}} state=present
      with_items:
        - glibc.i686
        - ncurses-libs.i686
    
    - name: Copy Sysconfig script
      copy: src=files/syscfg-V14.0-B15 dest=/tmp/syscfg-V14.0-B15 owner=root mode=0755

    - name: Register hostname
      shell:  hostname
      register: hostname

    - name: Run Sysconfig script to build hots.ini file
      #path: /tmp
    - script: /tmp/syscfg-V14.0-B15 /s {{hostname.stdout}}.ini /b

    - name: print out current Boot order for the node
      shell: grep -A 10 "bios\:\:bootorder" {{hostname.stdout}}.ini

    - name: change boot order to Hard Disk
      lineinfile: 
        dest: dest= /tmp/{{hostname.stdout}}.ini
        regexp: '(^IBA\s+(.+)\s+)[\d+]$'
        line: '\1 2'
        backrefs: yes
        state: present

      #lineinfile: dest= /tmp/{{hostname}}.ini regex='' line=''

    - name: Save and build ini file with new changes
      #path: /tmp
    - script: /tmp/syscfg-V14.0-B15 /r {{hostname.stdout}}.ini /b


